### ISSUE TITLE
New project setup

### ISSUE THREAD

**Issue by wuffo** [twfahey1/codespaces-lamp#1]
Opening this repo in codespaces, neither pantheon-init nor repair-codespace are recognized commands. Files and directories are not created within a .devcontainer folder. Cloning the repo into a new .devcontainer folder and rebuilding resulted in multiple errors prohibiting container creation. What am I doing wrong?

**Comment by twfahey1** [comment]
Ah… I believe it’s the Terminus installation bit… I recently have dusted this off and I had to tweak that with a new installation method… will update shortly

**Comment by twfahey1** [comment]
@wuffo If you give it a shot now, I believe it should work. If not, let me know the exact error you're seeing in the codespaces build log, and we could troubleshoot it from there.

**Comment by wuffo** [comment]
Same errors. Initial opening in codespaces does not appear to cause the typical build process, and no recognition of the commands, like pantheon init. Manually creating a .devcontainer folder and then cloning/rebuilding produces the following creation log:

```
2022-07-06 22:02:01.442Z: Configuration starting...
2022-07-06 22:02:16.770Z: @microsoft/vscode-dev-containers-cli 0.63.0.
2022-07-06 22:02:16.872Z: Start: Resolving Remote
2022-07-06 22:02:16.888Z: $ docker ps -q -a --filter label=Type=codespaces
2022-07-06 22:02:16.898Z: Stop (33 ms): Run: docker ps -q -a --filter label=Type=codespaces
2022-07-06 22:02:16.908Z: $ /usr/bin/node /usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /var/lib/docker/codespacemount/.persistedshare --container-data-folder .vscode-remote/data/Machine --container-system-data-folder /var/vscode-remote --workspace-folder /var/lib/docker/codespacemount/workspace/codespaces-lamp --id-label Type=codespaces --log-level info --log-format json --config /var/lib/docker/codespacemount/workspace/codespaces-lamp/.devcontainer/devcontainer.json --override-config /root/.codespaces/shared/merged_devcontainer.json --default-user-env-probe loginInteractiveShell --remove-existing-container --mount type=bind,source=/.codespaces/agent/mount/cache,target=/vscode --skip-post-create --update-remote-user-uid-default never --mount-workspace-git-root false
2022-07-06 22:02:16.932Z: @microsoft/vscode-dev-containers-cli 0.63.0.
2022-07-06 22:02:16.942Z: $ docker buildx version
2022-07-06 22:02:16.987Z: Stop (68 ms): Run: docker buildx version
2022-07-06 22:02:16.999Z: Start: Resolving Remote
2022-07-06 22:02:17.009Z: $ docker ps -q -a --filter label=Type=codespaces
2022-07-06 22:02:17.022Z: Stop (26 ms): Run: docker ps -q -a --filter label=Type=codespaces
2022-07-06 22:02:17.033Z: $ docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /var/lib/docker/codespacemount/workspace/codespaces-lamp/.devcontainer/Dockerfile -t vsc-codespaces-lamp-ad09fe911880b2f9680fff52eb75a1fa --build-arg VARIANT=buster /var/lib/docker/codespacemount/workspace/codespaces-lamp/.devcontainer
2022-07-06 22:02:17.492Z: #1 [internal] load .dockerignore
2022-07-06 22:02:17.604Z: #1 ...
2022-07-06 22:02:17.618Z: 
2022-07-06 22:02:17.633Z: #2 [internal] load build definition from Dockerfile
2022-07-06 22:02:17.659Z: #2 transferring dockerfile: 1.32kB done
2022-07-06 22:02:17.674Z: #2 DONE 0.3s
2022-07-06 22:02:17.690Z: 
2022-07-06 22:02:17.704Z: #1 [internal] load .dockerignore
2022-07-06 22:02:17.716Z: #1 transferring context: 2B done
2022-07-06 22:02:17.731Z: #1 DONE 0.3s
2022-07-06 22:02:17.742Z: 
2022-07-06 22:02:17.752Z: #3 [internal] load metadata for mcr.microsoft.com/vscode/devcontainers/base:0-buster
2022-07-06 22:02:18.600Z: #3 DONE 0.8s
2022-07-06 22:02:18.619Z: 
2022-07-06 22:02:18.646Z: #4 [internal] load build context
2022-07-06 22:02:18.665Z: #4 DONE 0.0s
2022-07-06 22:02:18.689Z: 
2022-07-06 22:02:18.709Z: #5 [ 1/10] FROM mcr.microsoft.com/vscode/devcontainers/base:0-buster@sha256:70857a013cfc2734125243cfc7229dba5e24e891cab8cbb85b67b0622b816c3f
2022-07-06 22:02:18.734Z: #5 resolve mcr.microsoft.com/vscode/devcontainers/base:0-buster@sha256:70857a013cfc2734125243cfc7229dba5e24e891cab8cbb85b67b0622b816c3f 0.0s done
2022-07-06 22:02:18.799Z: #5 sha256:70857a013cfc2734125243cfc7229dba5e24e891cab8cbb85b67b0622b816c3f 1.37kB / 1.37kB done
2022-07-06 22:02:18.813Z: #5 sha256:d5fc5eeba56decbe1a08f4cfd9ad8693dcc003213e71d3ad619c37c5ff9064d1 3.35kB / 3.35kB done
2022-07-06 22:02:18.838Z: #5 sha256:293ff1be7001d642a624409e2d5f90e7708ef7e6f1a75f4eb7362a9296e18d20 0B / 10.00MB 0.1s
2022-07-06 22:02:18.857Z: #5 sha256:ea267e4631a981caf2841a7e9a1faf29cef9d020c4378fc64845802d17586531 0B / 50.44MB 0.1s
2022-07-06 22:02:18.964Z: #5 ...
2022-07-06 22:02:18.975Z: 
2022-07-06 22:02:18.985Z: #4 [internal] load build context
2022-07-06 22:02:18.996Z: #4 transferring context: 9.44MB 0.1s done
2022-07-06 22:02:19.008Z: #4 DONE 0.3s
2022-07-06 22:02:19.049Z: 
2022-07-06 22:02:19.062Z: #5 [ 1/10] FROM mcr.microsoft.com/vscode/devcontainers/base:0-buster@sha256:70857a013cfc2734125243cfc7229dba5e24e891cab8cbb85b67b0622b816c3f
2022-07-06 22:02:19.127Z: #5 sha256:ea267e4631a981caf2841a7e9a1faf29cef9d020c4378fc64845802d17586531 14.68MB / 50.44MB 0.2s
2022-07-06 22:02:19.147Z: #5 sha256:8a014c92148934973210d840dc7cfed53e0afba38d839afaa48ed5150eae19af 0B / 7.86MB 0.2s
2022-07-06 22:02:19.164Z: #5 sha256:293ff1be7001d642a624409e2d5f90e7708ef7e6f1a75f4eb7362a9296e18d20 5.24MB / 10.00MB 0.3s
2022-07-06 22:02:19.183Z: #5 sha256:8a014c92148934973210d840dc7cfed53e0afba38d839afaa48ed5150eae19af 4.19MB / 7.86MB 0.3s
2022-07-06 22:02:19.245Z: #5 sha256:293ff1be7001d642a624409e2d5f90e7708ef7e6f1a75f4eb7362a9296e18d20 10.00MB / 10.00MB 0.5s done
2022-07-06 22:02:19.256Z: #5 sha256:ea267e4631a981caf2841a7e9a1faf29cef9d020c4378fc64845802d17586531 35.65MB / 50.44MB 0.5s
2022-07-06 22:02:19.266Z: #5 sha256:8a014c92148934973210d840dc7cfed53e0afba38d839afaa48ed5150eae19af 7.86MB / 7.86MB 0.4s done
2022-07-06 22:02:19.412Z: #5 sha256:ea267e4631a981caf2841a7e9a1faf29cef9d020c4378fc64845802d17586531 50.44MB / 50.44MB 0.7s
2022-07-06 22:02:19.525Z: #5 sha256:517acb796cdec889b57fa9f8b7768f26ba6f6cd9c3b9a40f59546e2c7ea4e351 0B / 6.03kB 0.7s
2022-07-06 22:02:19.540Z: #5 sha256:553b6e7640f3358cc58dddd1b33a74301fd9cf8b392e93f037f9e12d62f9a10d 0B / 97.47MB 0.7s
2022-07-06 22:02:19.636Z: #5 sha256:ea267e4631a981caf2841a7e9a1faf29cef9d020c4378fc64845802d17586531 50.44MB / 50.44MB 0.9s done
2022-07-06 22:02:19.647Z: #5 sha256:553b6e7640f3358cc58dddd1b33a74301fd9cf8b392e93f037f9e12d62f9a10d 6.29MB / 97.47MB 0.9s
2022-07-06 22:02:19.657Z: #5 extracting sha256:ea267e4631a981caf2841a7e9a1faf29cef9d020c4378fc64845802d17586531
2022-07-06 22:02:19.749Z: #5 sha256:517acb796cdec889b57fa9f8b7768f26ba6f6cd9c3b9a40f59546e2c7ea4e351 6.03kB / 6.03kB 1.0s done
2022-07-06 22:02:19.944Z: #5 sha256:553b6e7640f3358cc58dddd1b33a74301fd9cf8b392e93f037f9e12d62f9a10d 12.58MB / 97.47MB 1.2s
2022-07-06 22:02:20.393Z: #5 sha256:553b6e7640f3358cc58dddd1b33a74301fd9cf8b392e93f037f9e12d62f9a10d 31.46MB / 97.47MB 1.7s
2022-07-06 22:02:20.559Z: #5 sha256:553b6e7640f3358cc58dddd1b33a74301fd9cf8b392e93f037f9e12d62f9a10d 41.94MB / 97.47MB 1.8s
2022-07-06 22:02:21.069Z: #5 extracting sha256:ea267e4631a981caf2841a7e9a1faf29cef9d020c4378fc64845802d17586531 1.3s done
2022-07-06 22:02:21.352Z: #5 sha256:553b6e7640f3358cc58dddd1b33a74301fd9cf8b392e93f037f9e12d62f9a10d 48.23MB / 97.47MB 2.6s
2022-07-06 22:02:21.465Z: #5 sha256:553b6e7640f3358cc58dddd1b33a74301fd9cf8b392e93f037f9e12d62f9a10d 60.82MB / 97.47MB 2.7s
2022-07-06 22:02:21.483Z: #5 extracting sha256:8a014c92148934973210d840dc7cfed53e0afba38d839afaa48ed5150eae19af 0.1s
2022-07-06 22:02:21.576Z: #5 sha256:553b6e7640f3358cc58dddd1b33a74301fd9cf8b392e93f037f9e12d62f9a10d 69.21MB / 97.47MB 2.8s
2022-07-06 22:02:21.716Z: #5 sha256:553b6e7640f3358cc58dddd1b33a74301fd9cf8b392e93f037f9e12d62f9a10d 96.47MB / 97.47MB 3.0s
2022-07-06 22:02:22.378Z: #5 extracting sha256:8a014c92148934973210d840dc7cfed53e0afba38d839afaa48ed5150eae19af 0.2s done
2022-07-06 22:02:22.612Z: #5 sha256:553b6e7640f3358cc58dddd1b33a74301fd9cf8b392e93f037f9e12d62f9a10d 97.47MB / 97.47MB 3.7s done
2022-07-06 22:02:22.852Z: #5 extracting sha256:293ff1be7001d642a624409e2d5f90e7708ef7e6f1a75f4eb7362a9296e18d20
2022-07-06 22:02:23.104Z: #5 extracting sha256:293ff1be7001d642a624409e2d5f90e7708ef7e6f1a75f4eb7362a9296e18d20 0.2s done
2022-07-06 22:02:23.217Z: #5 extracting sha256:517acb796cdec889b57fa9f8b7768f26ba6f6cd9c3b9a40f59546e2c7ea4e351
2022-07-06 22:02:23.384Z: #5 extracting sha256:517acb796cdec889b57fa9f8b7768f26ba6f6cd9c3b9a40f59546e2c7ea4e351 done
2022-07-06 22:02:23.496Z: #5 extracting sha256:553b6e7640f3358cc58dddd1b33a74301fd9cf8b392e93f037f9e12d62f9a10d 0.1s
2022-07-06 22:02:26.323Z: #5 extracting sha256:553b6e7640f3358cc58dddd1b33a74301fd9cf8b392e93f037f9e12d62f9a10d 2.8s done
2022-07-06 22:02:28.732Z: #5 DONE 10.2s
2022-07-06 22:02:28.872Z: 
2022-07-06 22:02:28.884Z: #6 [ 2/10] RUN sudo apt -y install lsb-release apt-transport-https ca-certificates     && sudo wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg     && echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/php.list
2022-07-06 22:02:29.151Z: #6 0.379 
2022-07-06 22:02:29.163Z: #6 0.379 WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
2022-07-06 22:02:29.174Z: #6 0.379 
2022-07-06 22:02:29.295Z: #6 0.382 Reading package lists...
2022-07-06 22:02:29.306Z: #6 0.391 Building dependency tree...
2022-07-06 22:02:29.316Z: #6 0.392 Reading state information...
2022-07-06 22:02:29.326Z: #6 0.395 apt-transport-https is already the newest version (1.8.2.3).
2022-07-06 22:02:29.336Z: #6 0.395 ca-certificates is already the newest version (20200601~deb10u2).
2022-07-06 22:02:29.346Z: #6 0.395 lsb-release is already the newest version (10.2019051400).
2022-07-06 22:02:29.356Z: #6 0.395 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
2022-07-06 22:02:29.365Z: #6 0.402 --2022-07-06 22:02:29--  https://packages.sury.org/php/apt.gpg
2022-07-06 22:02:29.375Z: #6 0.408 Resolving packages.sury.org (packages.sury.org)... 
2022-07-06 22:02:29.447Z: 156.146.53.227
2022-07-06 22:02:29.458Z: #6 0.570 Connecting to packages.sury.org (packages.sury.org)|156.146.53.227|:443... connected.
2022-07-06 22:02:29.587Z: #6 0.697 HTTP request sent, awaiting response... 200 OK
2022-07-06 22:02:29.611Z: #6 0.742 Length: 1769 (1.7K) [application/octet-stream]
2022-07-06 22:02:29.623Z: #6 0.742 Saving to: '/etc/apt/trusted.gpg.d/php.gpg'
2022-07-06 22:02:29.633Z: #6 0.742 
2022-07-06 22:02:29.654Z: #6 0.742      0K .                                                     100% 41.8M=0s
2022-07-06 22:02:29.675Z: #6 0.742 
2022-07-06 22:02:29.691Z: #6 0.742 2022-07-06 22:02:29 (41.8 MB/s) - '/etc/apt/trusted.gpg.d/php.gpg' saved [1769/1769]
2022-07-06 22:02:29.712Z: #6 0.742 
2022-07-06 22:02:29.727Z: #6 0.774 deb https://packages.sury.org/php/ buster main
2022-07-06 22:02:29.756Z: #6 DONE 0.9s
2022-07-06 22:02:29.788Z: 
2022-07-06 22:02:29.821Z: #7 [ 3/10] RUN apt-get update && export DEBIAN_FRONTEND=noninteractive     && apt-get -y install --no-install-recommends php7.4 php7.4-bcmath php7.4-bz2 php7.4-intl php7.4-gd php7.4-mbstring php7.4-mysql php7.4-zip php7.4-dom php7.4-yaml php7.4-curl mariadb-server apache2 nodejs npm
2022-07-06 22:02:30.179Z: #7 0.506 Get:1 http://security.debian.org/debian-security buster/updates InRelease [65.4 kB]
2022-07-06 22:02:30.291Z: #7 0.507 Get:2 http://deb.debian.org/debian buster InRelease [122 kB]
2022-07-06 22:02:30.308Z: #7 0.522 Get:3 http://deb.debian.org/debian buster-updates InRelease [51.9 kB]
2022-07-06 22:02:30.318Z: #7 0.611 Get:4 http://security.debian.org/debian-security buster/updates/non-free amd64 Packages [556 B]
2022-07-06 22:02:30.383Z: #7 0.623 Get:5 http://security.debian.org/debian-security buster/updates/main amd64 Packages [334 kB]
2022-07-06 22:02:30.394Z: #7 0.712 Get:6 http://deb.debian.org/debian buster/main amd64 Packages [7911 kB]
2022-07-06 22:02:30.495Z: #7 0.807 Get:7 http://deb.debian.org/debian buster/contrib amd64 Packages [50.1 kB]
2022-07-06 22:02:30.539Z: #7 0.808 Get:8 http://deb.debian.org/debian buster/non-free amd64 Packages [87.7 kB]
2022-07-06 22:02:30.549Z: #7 0.822 Get:9 http://deb.debian.org/debian buster-updates/main amd64 Packages [8788 B]
2022-07-06 22:02:30.811Z: #7 1.025 Get:10 https://packages.sury.org/php buster InRelease [6837 B]
2022-07-06 22:02:30.951Z: #7 1.173 Get:11 https://packages.sury.org/php buster/main amd64 Packages [351 kB]
2022-07-06 22:02:31.707Z: #7 1.917 Fetched 8989 kB in 1s (6317 kB/s)
2022-07-06 22:02:31.724Z: #7 1.917 Reading package lists...
2022-07-06 22:02:32.127Z: 
2022-07-06 22:02:32.267Z: #7 2.475 Reading package lists...
2022-07-06 22:02:32.695Z: 
2022-07-06 22:02:32.707Z: #7 3.007 Building dependency tree...
2022-07-06 22:02:32.811Z: 
2022-07-06 22:02:32.822Z: #7 3.097 Reading state information...
2022-07-06 22:02:32.831Z: #7 3.137 Some packages could not be installed. This may mean that you have
2022-07-06 22:02:32.842Z: #7 3.137 requested an impossible situation or if you are using the unstable
2022-07-06 22:02:32.851Z: #7 3.137 distribution that some required packages have not yet been created
2022-07-06 22:02:32.861Z: #7 3.137 or been moved out of Incoming.
2022-07-06 22:02:32.871Z: #7 3.137 The following information may help to resolve the situation:
2022-07-06 22:02:32.886Z: #7 3.137 
2022-07-06 22:02:32.968Z: #7 3.137 The following packages have unmet dependencies:
2022-07-06 22:02:32.980Z: #7 3.184  php7.4-gd : Depends: libgd3 (>= 2.1.1) but it is not going to be installed
2022-07-06 22:02:32.998Z: #7 3.191 E: Unable to correct problems, you have held broken packages.
2022-07-06 22:02:33.059Z: #7 ERROR: executor failed running [/bin/sh -c apt-get update && export DEBIAN_FRONTEND=noninteractive     && apt-get -y install --no-install-recommends php7.4 php7.4-bcmath php7.4-bz2 php7.4-intl php7.4-gd php7.4-mbstring php7.4-mysql php7.4-zip php7.4-dom php7.4-yaml php7.4-curl mariadb-server apache2 nodejs npm]: exit code: 100
2022-07-06 22:02:33.077Z: ------
2022-07-06 22:02:33.093Z:  > [ 3/10] RUN apt-get update && export DEBIAN_FRONTEND=noninteractive     && apt-get -y install --no-install-recommends php7.4 php7.4-bcmath php7.4-bz2 php7.4-intl php7.4-gd php7.4-mbstring php7.4-mysql php7.4-zip php7.4-dom php7.4-yaml php7.4-curl mariadb-server apache2 nodejs npm:
2022-07-06 22:02:33.104Z: #7 3.097 Reading state information...
2022-07-06 22:02:33.121Z: #7 3.137 Some packages could not be installed. This may mean that you have
2022-07-06 22:02:33.137Z: #7 3.137 requested an impossible situation or if you are using the unstable
2022-07-06 22:02:33.152Z: #7 3.137 distribution that some required packages have not yet been created
2022-07-06 22:02:33.167Z: #7 3.137 or been moved out of Incoming.
2022-07-06 22:02:33.193Z: #7 3.137 The following information may help to resolve the situation:
2022-07-06 22:02:33.213Z: #7 3.137 
2022-07-06 22:02:33.227Z: #7 3.137 The following packages have unmet dependencies:
2022-07-06 22:02:33.242Z: #7 3.184  php7.4-gd : Depends: libgd3 (>= 2.1.1) but it is not going to be installed
2022-07-06 22:02:33.258Z: #7 3.191 E: Unable to correct problems, you have held broken packages.
2022-07-06 22:02:33.273Z: ------
2022-07-06 22:02:33.289Z: error: failed to solve: executor failed running [/bin/sh -c apt-get update && export DEBIAN_FRONTEND=noninteractive     && apt-get -y install --no-install-recommends php7.4 php7.4-bcmath php7.4-bz2 php7.4-intl php7.4-gd php7.4-mbstring php7.4-mysql php7.4-zip php7.4-dom php7.4-yaml php7.4-curl mariadb-server apache2 nodejs npm]: exit code: 100
2022-07-06 22:02:33.304Z: Stop (16021 ms): Run: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /var/lib/docker/codespacemount/workspace/codespaces-lamp/.devcontainer/Dockerfile -t vsc-codespaces-lamp-ad09fe911880b2f9680fff52eb75a1fa --build-arg VARIANT=buster /var/lib/docker/codespacemount/workspace/codespaces-lamp/.devcontainer
2022-07-06 22:02:33.319Z: Error: Command failed: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /var/lib/docker/codespacemount/workspace/codespaces-lamp/.devcontainer/Dockerfile -t vsc-codespaces-lamp-ad09fe911880b2f9680fff52eb75a1fa --build-arg VARIANT=buster /var/lib/docker/codespacemount/workspace/codespaces-lamp/.devcontainer
2022-07-06 22:02:33.334Z:     at jR (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:240:1143)
2022-07-06 22:02:33.349Z:     at processTicksAndRejections (internal/process/task_queues.js:95:5)
2022-07-06 22:02:33.365Z:     at async Uu (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:239:2142)
2022-07-06 22:02:33.380Z:     at async Jy (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:239:1168)
2022-07-06 22:02:33.395Z:     at async zR (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:245:2006)
2022-07-06 22:02:33.410Z:     at async nb (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:245:3110)
2022-07-06 22:02:33.425Z:     at async JR (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:245:13046)
2022-07-06 22:02:33.441Z:     at async KR (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:245:12802)
2022-07-06 22:02:33.461Z: Stop (16257 ms): Run: /usr/bin/node /usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /var/lib/docker/codespacemount/.persistedshare --container-data-folder .vscode-remote/data/Machine --container-system-data-folder /var/vscode-remote --workspace-folder /var/lib/docker/codespacemount/workspace/codespaces-lamp --id-label Type=codespaces --log-level info --log-format json --config /var/lib/docker/codespacemount/workspace/codespaces-lamp/.devcontainer/devcontainer.json --override-config /root/.codespaces/shared/merged_devcontainer.json --default-user-env-probe loginInteractiveShell --remove-existing-container --mount type=bind,source=/.codespaces/agent/mount/cache,target=/vscode --skip-post-create --update-remote-user-uid-default never --mount-workspace-git-root false
2022-07-06 22:02:33.476Z: Exit code 1
2022-07-06 22:02:33.494Z: Failed to create container.
2022-07-06 22:02:33.513Z: Error: Command failed: /usr/bin/node /usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /var/lib/docker/codespacemount/.persistedshare --container-data-folder .vscode-remote/data/Machine --container-system-data-folder /var/vscode-remote --workspace-folder /var/lib/docker/codespacemount/workspace/codespaces-lamp --id-label Type=codespaces --log-level info --log-format json --config /var/lib/docker/codespacemount/workspace/codespaces-lamp/.devcontainer/devcontainer.json --override-config /root/.codespaces/shared/merged_devcontainer.json --default-user-env-probe loginInteractiveShell --remove-existing-container --mount type=bind,source=/.codespaces/agent/mount/cache,target=/vscode --skip-post-create --update-remote-user-uid-default never --mount-workspace-git-root false
2022-07-06 22:02:33.526Z: Error Code: 1302
2022-07-06 22:02:33.540Z: Container creation failed.
2022-07-06 22:02:33.562Z: 
2022-07-06 22:02:33.577Z: Creating recovery container.
```

**Comment by twfahey1** [comment]
Ah interesting... looks like php is the issue... I am working to add this to a new project now, so I'll let you know what I find

**Comment by twfahey1** [comment]
Hmm, it's odd. I'm wondering if this could have been an issue with the package manager at the time you were installing - Just now, I fired up a new codespace, did the git clone of this repo, `mv`'ed it into `.devcontainer`, which gave me the "rebuild" prompt - and that just went through without a hitch. I'd be curious if you create an entirely new Codespace instance, assuming you are still getting the error - Let me know!

**Comment by wuffo** [comment]
Repeated the same steps, but using your updates, and it works for me too! Thanks.
Now, if only I could get WP running in codespaces. Nobody can get REST API/AJAX or cron to work....
